import { pgTable, text, serial, integer, boolean, timestamp, json } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
});

export const insertUserSchema = createInsertSchema(users).pick({
  username: true,
  password: true,
  email: true,
  name: true,
});

// Define temperature zones
export const temperatureZones = [
  "Dry",
  "Chiller (0–4°C)",
  "Freezer (-20°C)",
  "Wine (14°C)",
  "Confectionery (15–20°C)",
  "Pharma (2–8°C)",
] as const;

// Define status types
export const statusTypes = [
  "In Transit",
  "Delivered",
  "Awaiting Pickup",
] as const;

export const consignments = pgTable("consignments", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  consignmentNumber: text("consignment_number"),
  customerName: text("customer_name"),
  consignmentReference: text("consignment_reference"),
  trackingLink: text("tracking_link"),
  pickupAddress: text("pickup_address"),
  deliveryAddress: text("delivery_address"),
  status: text("status"),
  estimatedDeliveryDate: text("estimated_delivery_date"),
  deliveryDate: text("delivery_date"),
  dateDelivered: text("date_delivered"),
  consignmentRequiredDeliveryDate: text("consignment_required_delivery_date"),
  temperatureZone: text("temperature_zone"),
  lastKnownLocation: text("last_known_location"),
  deliveryRun: text("delivery_run"),
  quantity: integer("quantity"),
  pallets: integer("pallets"),
  spaces: integer("spaces"),
  cubicMeters: text("cubic_meters"),
  weightKg: text("weight_kg"),
  shipper: text("shipper"),
  receiver: text("receiver"),
  pickupCompany: text("pickup_company"),
  deliveryCompany: text("delivery_company"),
  pickupContactName: text("pickup_contact_name"),
  deliveryContactName: text("delivery_contact_name"),
  pickupContactPhone: text("pickup_contact_phone"),
  deliveryContactPhone: text("delivery_contact_phone"),
  specialInstructions: text("special_instructions"),
  productDescription: text("product_description"),
  deliveryInstructions: text("delivery_instructions"),
  pickupInstructions: text("pickup_instructions"),
  deliveryLivetrackLink: text("delivery_livetrack_link"),
  customerOrderNumber: text("customer_order_number"),
  documentString2: text("document_string2"),
  fromLocation: text("from_location"),
  toLocation: text("to_location"),
  groupCausalDeliveryOutcome: text("group_causal_delivery_outcome"),
  deliveryPlannedEta: text("delivery_planned_eta"),
  recordedTemperature: text("recorded_temperature"),
  quantityUnitOfMeasurement: text("quantity_unit_of_measurement"),
  quantityUnitOfMeasurement1: text("quantity_unit_of_measurement1"),
  quantityUnitOfMeasurement2: text("quantity_unit_of_measurement2"),
  route: text("route"),
  driver: text("driver"),
  vehicle: text("vehicle"),
  deliveryTime: text("delivery_time"),
  pickupTime: text("pickup_time"),
  consignmentType: text("consignment_type"),
  priority: text("priority"),
  deliveryZone: text("delivery_zone"),
  pickupZone: text("pickup_zone"),
  notes: text("notes"),
  customerReference: text("customer_reference"),
  invoiceNumber: text("invoice_number"),
  podSignature: text("pod_signature"),
  deliveryProof: text("delivery_proof"),
  // All 145 columns from your Excel file
  vehicleCode: text("vehicle_code"),
  deliveryLivetrackLink: text("delivery_livetrack_link"),
  deliveryEtaDeviation: text("delivery_eta_deviation"),
  requiredTags: text("required_tags"),
  receivedDeliveryPodFiles: text("received_delivery_pod_files"),
  orderCarrierEmail: text("order_carrier_email"),
  tripNumber: text("trip_number"),
  orderNumber: text("order_number"),
  from: text("from"),
  to: text("to"),
  carrier: text("carrier"),
  driver: text("driver"),
  documentString2: text("document_string2"),
  customerOrderNumber: text("customer_order_number"),
  deliveryPlannedEta: text("delivery_planned_eta"),
  deliveryCalculatedEta: text("delivery_calculated_eta"),
  timeSpentInTheUnloadingArea: text("time_spent_in_the_unloading_area"),
  deliveryOutcomeCausal: text("delivery_outcome_causal"),
  shipper: text("shipper"),
  deliveryArrivalDate: text("delivery_arrival_date"),
  deliveryOutcomeDate: text("delivery_outcome_date"),
  deliveryUnloadDate: text("delivery_unload_date"),
  groupCausalDeliveryOutcome: text("group_causal_delivery_outcome"),
  deliveryOutcomeNote: text("delivery_outcome_note"),
  deliveryLastPosition: text("delivery_last_position"),
  deliveryLastPositionDate: text("delivery_last_position_date"),
  pickupPlannedEta: text("pickup_planned_eta"),
  etaDeliveryOnDeparture: text("eta_delivery_on_departure"),
  deliveryLiveDistanceKm: text("delivery_live_distance_km"),
  deliveryDistanceKm: text("delivery_distance_km"),
  deliveryOutcomeTransmissionDate: text("delivery_outcome_transmission_date"),
  deliveryOutcomeReceiptDate: text("delivery_outcome_receipt_date"),
  deliveryUnloadSequence: text("delivery_unload_sequence"),
  deliveryTimeWindow: text("delivery_time_window"),
  pickupArrivalDate: text("pickup_arrival_date"),
  pickupOutcomeDate: text("pickup_outcome_date"),
  pickupLoadDate: text("pickup_load_date"),
  pickupOutcomeReason: text("pickup_outcome_reason"),
  groupCausalPickupOutcome: text("group_causal_pickup_outcome"),
  pickupOutcomeNote: text("pickup_outcome_note"),
  pickupLastPosition: text("pickup_last_position"),
  pickupLastPositionDate: text("pickup_last_position_date"),
  pickupCalculatedEta: text("pickup_calculated_eta"),
  etaPickupOnDeparture: text("eta_pickup_on_departure"),
  pickupLiveDistanceKm: text("pickup_live_distance_km"),
  pickupDistanceKm: text("pickup_distance_km"),
  pickupOutcomeReceiptDate: text("pickup_outcome_receipt_date"),
  pickupLoadSequence: text("pickup_load_sequence"),
  pickupTimeWindow: text("pickup_time_window"),
  fromMasterDataCode: text("from_master_data_code"),
  shipperCity: text("shipper_city"),
  shipperProvince: text("shipper_province"),
  shipperMasterDataCode: text("shipper_master_data_code"),
  depot: text("depot"),
  depotMasterDataCode: text("depot_master_data_code"),
  recipientMasterDataCode: text("recipient_master_data_code"),
  deliveryCity: text("delivery_city"),
  deliveryProvince: text("delivery_province"),
  carrierMasterDataCode: text("carrier_master_data_code"),
  subCarrier: text("sub_carrier"),
  subCarrierMasterDataCode: text("sub_carrier_master_data_code"),
  orderDate: text("order_date"),
  documentNote: text("document_note"),
  orderType: text("order_type"),
  orderSeries: text("order_series"),
  shipperOrderReferenceNumber: text("shipper_order_reference_number"),
  errorDescription: text("error_description"),
  driverPhone: text("driver_phone"),
  tractorLicensePlate: text("tractor_license_plate"),
  trailerLicensePlate: text("trailer_license_plate"),
  deliveryOutcome: text("delivery_outcome"),
  deliveryPunctuality: text("delivery_punctuality"),
  deliveryGeolocalizationState: text("delivery_geolocalization_state"),
  pickupOutcome: text("pickup_outcome"),
  pickupPunctuality: text("pickup_punctuality"),
  pickupGeolocationState: text("pickup_geolocation_state"),
  deliveryState: text("delivery_state"),
  pickupState: text("pickup_state"),
  destinationCoordinates: text("destination_coordinates"),
  departureCoordinates: text("departure_coordinates"),
  expectedTemperature: text("expected_temperature"),
  recordedTemperature: text("recorded_temperature"),
  deliveryMaximumDate: text("delivery_maximum_date"),
  deliveryMinimumDate: text("delivery_minimum_date"),
  pickupMinimumDate: text("pickup_minimum_date"),
  pickupMaximumDate: text("pickup_maximum_date"),
  quantityUnitOfMeasurement1: text("quantity_unit_of_measurement1"),
  quantityUnitOfMeasurement2: text("quantity_unit_of_measurement2"),
  weightKg: text("weight_kg"),
  volumeM3: text("volume_m3"),
  linearMetersM: text("linear_meters_m"),
  groundBases: text("ground_bases"),
  documentDate1: text("document_date1"),
  documentDate2: text("document_date2"),
  documentDate3: text("document_date3"),
  documentString1: text("document_string1"),
  documentString3: text("document_string3"),
  timeSpentInTheLoadingArea: text("time_spent_in_the_loading_area"),
  deliveryOutcomeInArea: text("delivery_outcome_in_area"),
  pickupOutcomeInArea: text("pickup_outcome_in_area"),
  deliveryOutcomePosition: text("delivery_outcome_position"),
  pickupOutcomePosition: text("pickup_outcome_position"),
  seals: text("seals"),
  taskId: text("task_id"),
  idCreationImport: text("id_creation_import"),
  expectedPaymentMethodCode: text("expected_payment_method_code"),
  expectedPaymentMethod: text("expected_payment_method"),
  deliveryOutcomeRegistrationDate: text("delivery_outcome_registration_date"),
  pickupOutcomeRegistrationDate: text("pickup_outcome_registration_date"),
  deliveryPinIsValid: text("delivery_pin_is_valid"),
  pickUpPinIsValid: text("pick_up_pin_is_valid"),
  expectedPaymentNotes: text("expected_payment_notes"),
  deliveryPodFiles: text("delivery_pod_files"),
  pickupPodFiles: text("pickup_pod_files"),
  departureDateInitiallyPlannedByTheContext: text("departure_date_initially_planned_by_the_context"),
  orderCarrierMobileTelephoneNumber: text("order_carrier_mobile_telephone_number"),
  orderCarrierTelephoneNumber: text("order_carrier_telephone_number"),
  orderPickupEmail: text("order_pickup_email"),
  orderPickupMobileTelephoneNumber: text("order_pickup_mobile_telephone_number"),
  orderPickupTelephoneNumber: text("order_pickup_telephone_number"),
  orderDeliveryEmail: text("order_delivery_email"),
  orderDeliveryMobileTelephoneNumber: text("order_delivery_mobile_telephone_number"),
  orderDeliveryTelephoneNumber: text("order_delivery_telephone_number"),
  orderSubCarrierEmail: text("order_sub_carrier_email"),
  orderSubCarrierMobileTelephoneNumber: text("order_sub_carrier_mobile_telephone_number"),
  orderSubCarrierTelephoneNumber: text("order_sub_carrier_telephone_number"),
  orderShipperEmail: text("order_shipper_email"),
  orderShipperMobileTelephoneNumber: text("order_shipper_mobile_telephone_number"),
  orderShipperTelephoneNumber: text("order_shipper_telephone_number"),
  forbiddenTags: text("forbidden_tags"),
  pickupPlannedServiceTime: text("pickup_planned_service_time"),
  deliveryPlannedServiceTime: text("delivery_planned_service_time"),
  externalReference: text("external_reference"),
  depotPhoneNumberSpecifiedInTheOrder: text("depot_phone_number_specified_in_the_order"),
  depotMobilePhoneNumberSpecifiedInTheOrder: text("depot_mobile_phone_number_specified_in_the_order"),
  receivedPickupPodFiles: text("received_pickup_pod_files"),
  requiredTagsDescription: text("required_tags_description"),
  forbiddenTagsDescription: text("forbidden_tags_description"),
  fromPostalCode: text("from_postal_code"),
  toPostalCode: text("to_postal_code"),
  fromCountry: text("from_country"),
  toCountry: text("to_country"),
  pickupEtaDeviation: text("pickup_eta_deviation"),
  pickupLivetrackLink: text("pickup_livetrack_link"),
  vehicleDescription: text("vehicle_description"),
  events: text("events").default('[]'),
});

export const insertConsignmentSchema = createInsertSchema(consignments).pick({
  consignmentNumber: true,
  userId: true,
  customerName: true,
  pickupAddress: true,
  deliveryAddress: true,
  status: true,
  estimatedDeliveryDate: true,
  temperatureZone: true,
  lastKnownLocation: true,
  events: true,
});

export type ConsignmentEvent = {
  timestamp: string;
  description: string;
  location: string;
  type: string;
};

export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;
export type InsertConsignment = z.infer<typeof insertConsignmentSchema>;
export type Consignment = typeof consignments.$inferSelect;
